name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create release tag
        id: tag
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: build-hugo-docs
          changelog-path: CHANGELOG.md
